### ISSUE TITLE
> and < symbols are not supported

### ISSUE THREAD

**Issue by redahe** [bpsm/edn-java#40]
ScannerImpl does not recognize symbols '>' and '<'.

**Comment by bpsm** [comment]
Wow, you're quite correct. I don't know how I missed that. Thanks for the report!

**Comment by bpsm** [comment]
I've merged in your fix for release with 0.4.5. I hope to get it out by Wednesday. Currently Sonatype is down for me. Also, I've discovered that I've upgraded my primary dev machine past JDK 1.6, but I want to keep edn-java 1.6 compatible, so I think it's time I set up a small VM for that purpose.

**Comment by bpsm** [comment]
0.4.5 has been released via oss.sonatype.org it should appear in maven central in the next day or so.
