### ISSUE TITLE
Version 1.0?

### ISSUE THREAD

**Issue by nicobao** [bpsm/edn-java#58]
Hi,
Thanks for the hard work you put to make this awesome library.
I see the library is at version 0.6, and no commit since summer last year.
Is the library stable enough to be used as is? Are  there known problems to be aware of? 
I am still in the process of learning - but I am happy to help.

With kind regards,
Nicolas

**Comment by bpsm** [comment]
Here's the plan: I'll next release issues 59 and 60, probably as 0.7. Issue 60 (unicode escaped character literals \uXXXX), in particular, suggests that I should re-read the edn-format spec to make sure I haven't missed something else. After that, a 1.0 release seems like a reasonable thing to do.
