### ISSUE TITLE
0.7.0 or 0.7.1

### ISSUE THREAD

**Issue by avodonosov** [bpsm/edn-java#66]
The pom.xml contains version 0.7.0, but the README mentions 0.7.1.

Is that a mistake in README? Or the pom.xml change is not pushed to github?

**Comment by bpsm** [comment]
Good catch, thanks.

0.7.0 was never published to Maven Central because of complications with GPG. 0.7.1 is on Maven Central, but I forgot to merge the 0.7.1 tag back to master after doing that. Fixed.
